name: todo_shelf_modular
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  mocktail: ^0.2.0
  test: ^1.19.3
dependencies: 
  crypto: ^3.0.1
  jaguar_jwt: ^3.0.0
  postgres: ^2.4.2
  shelf: ^1.2.0
  shelf_modular: ^1.0.0
  dotenv: ^3.0.0
