name: todo_shelf_modular
description: A simple command-line application.
version: 1.0.1+4
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  mocktail: ^0.2.0
  test: ^1.19.3
dependencies: 
  crypto: ^3.0.1
  jaguar_jwt: ^3.0.0
  postgres: ^2.4.2
  shelf: ^1.2.0
  shelf_modular: 2.0.0-dev.3
  dotenv: ^3.0.0
  jwt_decoder: ^2.0.1
  shelf_cors_headers: ^0.1.3
